apiVersion: v1
kind: Service
metadata:
  name: livegrep-frontend-nodeport
  labels:
    livegrep.service: livegrep-frontend
spec:
  type: NodePort
  ports:
  - nodePort: 31555
    port: 8910
    protocol: TCP
    targetPort: 8910
  selector:
    livegrep.service: livegrep-frontend
